const data = {
    users: [
        {
            name: 'Kamal Udddin',
            phone: '01700000000',
            address: 'Mirpur, Dhaka',
            password: '123456',
            isAdmin: true,
        },
        {
            name: 'Rana Khan',
            phone: '01700000001',
            address: 'Dhanmondi, Dhaka',
            password: '123456',
            isAdmin: false,
        },
        {
            name: 'Jannati Akter',
            phone: '01700000002',
            address: 'Savar, Dhaka',
            password: '123456',
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirt',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Adiddas',
            rating: 4.8,
            numReviews: 20,
            countInStock: 10,
            description: 'A popular shirt'
        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirt',
            image: '/images/shirt3.jpg',
            price: 90,
            brand: 'Reaymon',
            rating: 4.4,
            numReviews: 12,
            countInStock: 30,
            description: 'A popular shirt'
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 100,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular pants'
        },
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 10,
            brand: 'Oliver',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular pants'
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 60,
            brand: 'Raymon',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular pants'
        },
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirt',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Adiddas',
            rating: 4.8,
            numReviews: 20,
            countInStock: 10,
            description: 'A popular shirt'
        },
    ]
};
export default data;

